# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=20)),
                ('company_description', models.CharField(max_length=250)),
                ('company_type', models.CharField(max_length=10)),
                ('depts', models.CharField(max_length=250)),
                ('date_of_visit', models.CharField(max_length=250)),
                ('package', models.FloatField()),
                ('cgpa', models.FloatField()),
                ('contact_1', models.BigIntegerField()),
                ('contact_2', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('bond', models.FloatField()),
                ('rating', models.FloatField()),
                ('website', models.URLField()),
                ('company_logo', models.FileField(upload_to=b'')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
