# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-18 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='isApproved',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
