# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-18 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0002_role_isapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='isApproved',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
