# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-19 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0003_auto_20171118_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=10)),
                ('rollno', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('year', models.IntegerField(max_length=1)),
                ('contact', models.BigIntegerField()),
                ('profilepicture', models.FileField(blank=True, null=True, upload_to=b'')),
                ('resume', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
    ]
