# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-19 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0004_admindetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetails',
            name='year',
            field=models.IntegerField(),
        ),
    ]
