# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0006_auto_20171120_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetails',
            name='dob',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='profilepicture',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='admindetails',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
