# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-20 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0007_auto_20171120_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admindetails',
            old_name='dob',
            new_name='birthday',
        ),
    ]
