# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-20 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userModule', '0008_auto_20171120_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindetails',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
