# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-20 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0009_admindetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindetails',
            name='resume',
        ),
    ]
